type Bookmark {
    id: ID!
    title: String!
    url: String!
}

input AddBookmark {
    title: String!
    url: String!
    user: String!
}

input UpdateBookmark {
    id: ID!,
    title: String!,
    url: String!
}

type Query {
    getBookmark(user: String!): [Bookmark]
}

type Mutation {
    addBookmark(bookmark: AddBookmark!): Bookmark
    updateBookmark(editedBookmark: UpdateBookmark!): Bookmark
    deleteBookmark(bookmarkId: String!): String
}